import fs from 'fs-extra';
import path from 'path';
import { scanDirectory } from '../scanners/index';
import { analyzeFunction } from '../analyzers/index';
import { getConfig } from '../config/index';

export async function generateDocs(): Promise<void> {
  const config = getConfig();
  const parsedFiles = await scanDirectory('src'); // defaults to src, or passed dir
  
  const docsDir = path.join(process.cwd(), 'docs');
  await fs.ensureDir(docsDir);

  let mdContent = '# FuncPilot Codebase Documentation\n\n';
  mdContent += '> Auto-generated by FuncPilot\n\n';

  let totalFunctions = 0;
  let totalIssues = 0;

  for (const file of parsedFiles) {
    if (file.functions.length === 0) continue;
    
    mdContent += `## File: \`${file.file}\`\n\n`;
    
    if (file.classes.length > 0) {
      mdContent += `### Classes\n`;
      for (const cls of file.classes) {
        mdContent += `- **${cls.name}**\n`;
      }
      mdContent += '\n';
    }

    mdContent += `### Functions\n`;
    for (const func of file.functions) {
      totalFunctions++;
      const isAsync = func.isAsync ? 'async ' : '';
      const params = func.params.join(', ');
      mdContent += `- **\`${isAsync}${func.name}(${params})\`** (${func.type})\n`;

      const issues = analyzeFunction(func);
      if (issues.length > 0) {
        mdContent += `  - ⚠️ **Issues detected:**\n`;
        issues.forEach(issue => {
          totalIssues++;
          mdContent += `    - ${issue.issue} (Suggestion: ${issue.suggestion})\n`;
        });
      }
    }
    mdContent += '\n';
  }

  mdContent = `# Summary\n- Total Analyzed Functions: ${totalFunctions}\n- Total Detected Issues: ${totalIssues}\n\n` + mdContent;

  const docPath = path.join(docsDir, 'CODEBASE.md');
  await fs.writeFile(docPath, mdContent, 'utf-8');
}
